import { MigrationInterface, QueryRunner } from "typeorm";

export class UpdateTradeRecordsPK1753244148163 implements MigrationInterface {
    name = 'UpdateTradeRecordsPK1753244148163'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX "public"."IDX_01d27c3ecdcd58f90fde823a5e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_67be60abf476a42852abbb8e0e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_44b879cf885ec02d26b4e2179a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a8504c4f82a210518771bfdaa6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_693a2ad604fda78542ca8316cc"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ff72dcc08294e836c7343c5c15"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_335ba83aef8b6ec0bd73ddf1e5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1b31b2673e7abf253a461ef6f1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5028cba304ec5e04c348d549db"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4f8e670833e3cfcfb448384a21"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e1d0469ac809a1f1982a3f9df5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8fa57a155cd5feb48a664182d7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_741dbb8536837446b071647919"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0f78d71cdeb2f0a388d9953651"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4b19940b9452fd568f30402215"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b1c6fa2325092501aa26020ec0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_53315d1765e513e27ea6cb8536"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_476dd4ecc6a63a6b0d27fbfdb2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c7d0f3942e81c79410044b0067"`);
        await queryRunner.query(`ALTER TABLE "spot_trade_records" ADD "accountId" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "spot_trade_records" ADD "userId" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "bitcoin_transactions" ADD "accountId" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "bitcoin_transactions" ADD "userId" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "bitcoin_transactions" ADD "tradeType" character varying(20)`);
        await queryRunner.query(`ALTER TABLE "futures_trade_records" ADD "accountId" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "futures_trade_records" ADD "userId" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "spot_trade_records" DROP CONSTRAINT "PK_c9bbbb130a6214a648d3774b8ea"`);
        await queryRunner.query(`ALTER TABLE "spot_trade_records" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "spot_trade_records" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "spot_trade_records" ADD CONSTRAINT "PK_c9bbbb130a6214a648d3774b8ea" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "bitcoin_transactions" DROP CONSTRAINT "PK_7c08599a3d5ed67350f8d1ccc5c"`);
        await queryRunner.query(`ALTER TABLE "bitcoin_transactions" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "bitcoin_transactions" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "bitcoin_transactions" ADD CONSTRAINT "PK_7c08599a3d5ed67350f8d1ccc5c" PRIMARY KEY ("id")`);
        await queryRunner.query(`DROP INDEX "public"."idx_btc_spot_trade"`);
        await queryRunner.query(`ALTER TABLE "bitcoin_transactions" DROP COLUMN "relatedSpotTradeId"`);
        await queryRunner.query(`ALTER TABLE "bitcoin_transactions" ADD "relatedSpotTradeId" integer`);
        await queryRunner.query(`DROP INDEX "public"."idx_btc_futures_trade"`);
        await queryRunner.query(`ALTER TABLE "bitcoin_transactions" DROP COLUMN "relatedFuturesTradeId"`);
        await queryRunner.query(`ALTER TABLE "bitcoin_transactions" ADD "relatedFuturesTradeId" integer`);
        await queryRunner.query(`ALTER TABLE "futures_trade_records" DROP CONSTRAINT "PK_db88b2b3960399e50c8e69e8ded"`);
        await queryRunner.query(`ALTER TABLE "futures_trade_records" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "futures_trade_records" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "futures_trade_records" ADD CONSTRAINT "PK_db88b2b3960399e50c8e69e8ded" PRIMARY KEY ("id")`);
        await queryRunner.query(`CREATE INDEX "idx_spot_account" ON "spot_trade_records" ("accountId") `);
        await queryRunner.query(`CREATE INDEX "idx_spot_symbol" ON "spot_trade_records" ("symbol") `);
        await queryRunner.query(`CREATE INDEX "idx_spot_order_id" ON "spot_trade_records" ("orderId") `);
        await queryRunner.query(`CREATE INDEX "idx_spot_source" ON "spot_trade_records" ("source") `);
        await queryRunner.query(`CREATE INDEX "idx_spot_executed_at" ON "spot_trade_records" ("executedAt") `);
        await queryRunner.query(`CREATE INDEX "idx_btc_account" ON "bitcoin_transactions" ("accountId") `);
        await queryRunner.query(`CREATE INDEX "idx_btc_tx_id" ON "bitcoin_transactions" ("txid") `);
        await queryRunner.query(`CREATE INDEX "idx_btc_block_height" ON "bitcoin_transactions" ("blockHeight") `);
        await queryRunner.query(`CREATE INDEX "idx_btc_timestamp" ON "bitcoin_transactions" ("timestamp") `);
        await queryRunner.query(`CREATE INDEX "idx_btc_purpose" ON "bitcoin_transactions" ("purpose") `);
        await queryRunner.query(`CREATE INDEX "idx_btc_spot_trade_id" ON "bitcoin_transactions" ("relatedSpotTradeId") `);
        await queryRunner.query(`CREATE INDEX "idx_btc_futures_trade_id" ON "bitcoin_transactions" ("relatedFuturesTradeId") `);
        await queryRunner.query(`CREATE INDEX "idx_btc_trade_type" ON "bitcoin_transactions" ("tradeType") `);
        await queryRunner.query(`CREATE INDEX "idx_btc_is_parsed" ON "bitcoin_transactions" ("isParsed") `);
        await queryRunner.query(`CREATE INDEX "idx_btc_futures_trade" ON "bitcoin_transactions" ("relatedFuturesTradeId") `);
        await queryRunner.query(`CREATE INDEX "idx_btc_spot_trade" ON "bitcoin_transactions" ("relatedSpotTradeId") `);
        await queryRunner.query(`CREATE INDEX "idx_futures_account" ON "futures_trade_records" ("accountId") `);
        await queryRunner.query(`CREATE INDEX "idx_futures_position_side" ON "futures_trade_records" ("positionSide") `);
        await queryRunner.query(`CREATE INDEX "idx_futures_closed_at" ON "futures_trade_records" ("closedAt") `);
        await queryRunner.query(`CREATE INDEX "idx_futures_liquidated" ON "futures_trade_records" ("isLiquidated") `);
        await queryRunner.query(`CREATE INDEX "idx_futures_closed" ON "futures_trade_records" ("isClosed") `);
        await queryRunner.query(`CREATE INDEX "idx_futures_executed_at" ON "futures_trade_records" ("executedAt") `);
        await queryRunner.query(`CREATE INDEX "idx_candle_created_at" ON "candle_15m" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "idx_candle_symbol_market_time" ON "candle_15m" ("symbol", "market", "openTime") `);
        await queryRunner.query(`CREATE INDEX "idx_candle_symbol_market" ON "candle_15m" ("symbol", "market") `);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX "public"."idx_candle_symbol_market"`);
        await queryRunner.query(`DROP INDEX "public"."idx_candle_symbol_market_time"`);
        await queryRunner.query(`DROP INDEX "public"."idx_candle_created_at"`);
        await queryRunner.query(`DROP INDEX "public"."idx_futures_executed_at"`);
        await queryRunner.query(`DROP INDEX "public"."idx_futures_closed"`);
        await queryRunner.query(`DROP INDEX "public"."idx_futures_liquidated"`);
        await queryRunner.query(`DROP INDEX "public"."idx_futures_closed_at"`);
        await queryRunner.query(`DROP INDEX "public"."idx_futures_position_side"`);
        await queryRunner.query(`DROP INDEX "public"."idx_futures_account"`);
        await queryRunner.query(`DROP INDEX "public"."idx_btc_spot_trade"`);
        await queryRunner.query(`DROP INDEX "public"."idx_btc_futures_trade"`);
        await queryRunner.query(`DROP INDEX "public"."idx_btc_is_parsed"`);
        await queryRunner.query(`DROP INDEX "public"."idx_btc_trade_type"`);
        await queryRunner.query(`DROP INDEX "public"."idx_btc_futures_trade_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_btc_spot_trade_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_btc_purpose"`);
        await queryRunner.query(`DROP INDEX "public"."idx_btc_timestamp"`);
        await queryRunner.query(`DROP INDEX "public"."idx_btc_block_height"`);
        await queryRunner.query(`DROP INDEX "public"."idx_btc_tx_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_btc_account"`);
        await queryRunner.query(`DROP INDEX "public"."idx_spot_executed_at"`);
        await queryRunner.query(`DROP INDEX "public"."idx_spot_source"`);
        await queryRunner.query(`DROP INDEX "public"."idx_spot_order_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_spot_symbol"`);
        await queryRunner.query(`DROP INDEX "public"."idx_spot_account"`);
        await queryRunner.query(`ALTER TABLE "futures_trade_records" DROP CONSTRAINT "PK_db88b2b3960399e50c8e69e8ded"`);
        await queryRunner.query(`ALTER TABLE "futures_trade_records" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "futures_trade_records" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "futures_trade_records" ADD CONSTRAINT "PK_db88b2b3960399e50c8e69e8ded" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "bitcoin_transactions" DROP COLUMN "relatedFuturesTradeId"`);
        await queryRunner.query(`ALTER TABLE "bitcoin_transactions" ADD "relatedFuturesTradeId" uuid`);
        await queryRunner.query(`CREATE INDEX "idx_btc_futures_trade" ON "bitcoin_transactions" ("relatedFuturesTradeId") `);
        await queryRunner.query(`ALTER TABLE "bitcoin_transactions" DROP COLUMN "relatedSpotTradeId"`);
        await queryRunner.query(`ALTER TABLE "bitcoin_transactions" ADD "relatedSpotTradeId" uuid`);
        await queryRunner.query(`CREATE INDEX "idx_btc_spot_trade" ON "bitcoin_transactions" ("relatedSpotTradeId") `);
        await queryRunner.query(`ALTER TABLE "bitcoin_transactions" DROP CONSTRAINT "PK_7c08599a3d5ed67350f8d1ccc5c"`);
        await queryRunner.query(`ALTER TABLE "bitcoin_transactions" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "bitcoin_transactions" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "bitcoin_transactions" ADD CONSTRAINT "PK_7c08599a3d5ed67350f8d1ccc5c" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "spot_trade_records" DROP CONSTRAINT "PK_c9bbbb130a6214a648d3774b8ea"`);
        await queryRunner.query(`ALTER TABLE "spot_trade_records" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "spot_trade_records" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "spot_trade_records" ADD CONSTRAINT "PK_c9bbbb130a6214a648d3774b8ea" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "futures_trade_records" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "futures_trade_records" DROP COLUMN "accountId"`);
        await queryRunner.query(`ALTER TABLE "bitcoin_transactions" DROP COLUMN "tradeType"`);
        await queryRunner.query(`ALTER TABLE "bitcoin_transactions" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "bitcoin_transactions" DROP COLUMN "accountId"`);
        await queryRunner.query(`ALTER TABLE "spot_trade_records" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "spot_trade_records" DROP COLUMN "accountId"`);
        await queryRunner.query(`CREATE INDEX "IDX_c7d0f3942e81c79410044b0067" ON "candle_15m" ("symbol", "market") `);
        await queryRunner.query(`CREATE INDEX "IDX_476dd4ecc6a63a6b0d27fbfdb2" ON "candle_15m" ("symbol", "market", "openTime") `);
        await queryRunner.query(`CREATE INDEX "IDX_53315d1765e513e27ea6cb8536" ON "candle_15m" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_b1c6fa2325092501aa26020ec0" ON "futures_trade_records" ("executedAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_4b19940b9452fd568f30402215" ON "futures_trade_records" ("isClosed") `);
        await queryRunner.query(`CREATE INDEX "IDX_0f78d71cdeb2f0a388d9953651" ON "futures_trade_records" ("isLiquidated") `);
        await queryRunner.query(`CREATE INDEX "IDX_741dbb8536837446b071647919" ON "futures_trade_records" ("closedAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_8fa57a155cd5feb48a664182d7" ON "futures_trade_records" ("positionSide") `);
        await queryRunner.query(`CREATE INDEX "IDX_e1d0469ac809a1f1982a3f9df5" ON "bitcoin_transactions" ("isParsed") `);
        await queryRunner.query(`CREATE INDEX "IDX_4f8e670833e3cfcfb448384a21" ON "bitcoin_transactions" ("relatedFuturesTradeId") `);
        await queryRunner.query(`CREATE INDEX "IDX_5028cba304ec5e04c348d549db" ON "bitcoin_transactions" ("relatedSpotTradeId") `);
        await queryRunner.query(`CREATE INDEX "IDX_1b31b2673e7abf253a461ef6f1" ON "bitcoin_transactions" ("purpose") `);
        await queryRunner.query(`CREATE INDEX "IDX_335ba83aef8b6ec0bd73ddf1e5" ON "bitcoin_transactions" ("timestamp") `);
        await queryRunner.query(`CREATE INDEX "IDX_ff72dcc08294e836c7343c5c15" ON "bitcoin_transactions" ("blockHeight") `);
        await queryRunner.query(`CREATE INDEX "IDX_693a2ad604fda78542ca8316cc" ON "bitcoin_transactions" ("txid") `);
        await queryRunner.query(`CREATE INDEX "IDX_a8504c4f82a210518771bfdaa6" ON "spot_trade_records" ("executedAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_44b879cf885ec02d26b4e2179a" ON "spot_trade_records" ("source") `);
        await queryRunner.query(`CREATE INDEX "IDX_67be60abf476a42852abbb8e0e" ON "spot_trade_records" ("symbol") `);
        await queryRunner.query(`CREATE INDEX "IDX_01d27c3ecdcd58f90fde823a5e" ON "spot_trade_records" ("orderId") `);
    }

}
